### Get ledger entries for account 2
GET http://localhost:8080/transactions?accountId=2
Content-Type: application/json

### Add a transaction
POST http://localhost:8080/transactions
Content-Type: application/json

{
  "fromAccountId": 1,
  "toAccountId": 2,
  "date": 123,
  "descr": "Some transaction",
  "cents": 999
}

### Update a transaction
PUT http://localhost:8080/transactions/7
Content-Type: application/json

{
  "fromAccountId": 3,
  "toAccountId": 4,
  "date": 234,
  "descr": "Some transaction changed",
  "cents": 888
}

### Delete a transaction
DELETE http://localhost:8080/transactions/7
